CREATE TABLE Customer (
  id INTEGER PRIMARY KEY,
  firstName VARCHAR(50),
  lastName VARCHAR(50),
  email VARCHAR(20),
  phone CHAR(10),
  streetAddress VARCHAR(50),
  city VARCHAR(10),
  state VARCHAR(5),
  postCode CHAR(6),
  country VARCHAR(10),
  userId VARCHAR(20),
  password VARCHAR(30)
);

CREATE TABLE PaymentMethod(
  id INTEGER PRIMARY KEY,
  type VARCHAR(10),
  number CHAR(16),
  expiryDate DATE,
  cusId INTEGER NOT NULL,
  FOREIGN KEY (cusId) REFERENCES Customer(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Warehouse(
  id INTEGER PRIMARY KEY,
  name VARCHAR(50)
);

CREATE TABLE Category(
  id INTEGER PRIMARY KEY,
  name VARCHAR(10)
);

CREATE TABLE Product(
  id INTEGER PRIMARY KEY,
  name VARCHAR(10),
  price DECIMAL(9,2),
  imageURL VARCHAR(30),
  image BLOB,
  description VARCHAR(5),
  categoryid INTEGER NOT NULL,
  FOREIGN KEY (categoryid) REFERENCES Category(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Review(
  id INTEGER PRIMARY KEY,
  rating INTEGER CHECK (rating BETWEEN 1 AND 5),
  comment VARCHAR(50),
  date DATE,
  cusId INTEGER NOT NULL,
  prodId INTEGER NOT NULL,
  FOREIGN KEY (cusId) REFERENCES Customer(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (prodId) REFERENCES Product(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE Shipment(
  id INTEGER PRIMARY KEY,
  date DATE,
  description VARCHAR(50),
  whId INTEGER NOT NULL,
  FOREIGN KEY (whId) REFERENCES Warehouse(id)
);

CREATE TABLE OrderSummary(
  id INTEGER PRIMARY KEY,
  date DATE,
  totalAmount DECIMAL(9,2),
  shipToAddress VARCHAR(50),
  shipToCity VARCHAR(10),
  shipToState VARCHAR(5),
  shipToCountry VARCHAR(10),
  shipToPostCode VARCHAR(6),
  custId INTEGER NOT NULL,
  shipId INTEGER NOT NULL,
  FOREIGN KEY (custId) REFERENCES Customer(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (shipId) REFERENCES Shipment(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE OrderProduct(
  quantity INTEGER,
  price DECIMAL(9,2),
  prodId INTEGER NOT NULL,
  orderId INTEGER NOT NULL,
  PRIMARY KEY (prodId, orderId),
  FOREIGN KEY (prodId) REFERENCES Product(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (orderId) REFERENCES OrderSummary(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);



CREATE TABLE ProductInventory(
  quantity INTEGER,
  prodId INTEGER NOT NULL,
  whId INTEGER NOT NULL,
  PRIMARY KEY (prodId, whId),
  FOREIGN KEY (prodId) REFERENCES Product(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (whId) REFERENCES Warehouse(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);


CREATE TABLE InCart(
  quantity INTEGER,
  price DECIMAL(9,2),
  prodId INTEGER NOT NULL,
  custId INTEGER NOT NULL,
  PRIMARY KEY (prodId, custId),
  FOREIGN KEY (prodId) REFERENCES Product(id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (custId) REFERENCES Customer(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);



